footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.42, 0.25], [0.42, -0.25]]  # if the robot is not circular

footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 7.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
